import {
  flattenKeys,
  generatedTypesPath,
  getStructure,
  readLocaleNamespaceJson,
  sorted,
  success,
  writeTextFile,
} from './i18n-shared.mjs';

function escapeQuote(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function main() {
  const { fallbackLocale, namespaces } = getStructure();
  const keys = [];

  for (const namespace of namespaces) {
    const payload = readLocaleNamespaceJson(fallbackLocale, namespace);
    const flattened = sorted(flattenKeys(payload));
    for (const key of flattened) {
      keys.push(`${namespace}.${key}`);
    }
  }

  const union =
    keys.length > 0
      ? keys.map((key) => `  | "${escapeQuote(key)}"`).join('\n')
      : '  | never';

  const content = `/* AUTO-GENERATED BY \`pnpm i18n:types\`. DO NOT EDIT MANUALLY. */

export type I18nTranslationKey =
${union};
`;

  writeTextFile(generatedTypesPath, content);
  success(`i18n types generated (${keys.length} keys).`);
}

main();
