/* AUTO-GENERATED BY `pnpm i18n:types`. DO NOT EDIT MANUALLY. */

export type I18nTranslationKey =
  | "common.checkApiHealth"
  | "common.language"
  | "common.languages.english"
  | "common.languages.ukrainian"
  | "common.ok"
  | "errors.accessDenied"
  | "errors.notFound"
  | "validation.required";
