/* AUTO-GENERATED BY `pnpm i18n:types`. DO NOT EDIT MANUALLY. */

export type I18nTranslationKey =
  | "common.checkApiHealth"
  | "common.checkDatabase"
  | "common.checkErrorEnvelope"
  | "common.checkValidation"
  | "common.language"
  | "common.languages.english"
  | "common.ok"
  | "common.probes.error"
  | "errors.accessDenied"
  | "errors.emailAlreadyExists"
  | "errors.notFound"
  | "validation.required";
