/* AUTO-GENERATED BY `pnpm i18n:sync`. DO NOT EDIT MANUALLY. */

export const I18N_LOCALES = ["en"] as const;
export const I18N_NAMESPACES = ["common", "errors", "validation"] as const;

export type I18nLocale = (typeof I18N_LOCALES)[number];
export type I18nNamespace = (typeof I18N_NAMESPACES)[number];
