export const COMMUNICATIONS_EMAIL_PROVIDER = 'FORGEON_COMMUNICATIONS_EMAIL_PROVIDER';
export const COMMUNICATIONS_SMS_PROVIDER = 'FORGEON_COMMUNICATIONS_SMS_PROVIDER';
export const COMMUNICATIONS_PUSH_PROVIDER = 'FORGEON_COMMUNICATIONS_PUSH_PROVIDER';
